### ISSUE TITLE
Why the t_correct is larger than t_wrong in MSE loss function

### ISSUE THREAD

**Issue by Xinhu-L** [JulianGoeltz/fastAndDeep#7]
Hi, I noticed that in the default config files, the t_correct is larger than t_wrong, which means that the loss function implies the the right spike comes later( if I understand correctly).
```YAML
  loss:
    type: MSE
    t_correct: 1.7
    t_wrong: 1.0
    # t_correct: 1.0
    # t_wrong: 2.0
```
But I think that the t_correct should be smaller than the t_wrong to train the right spike to come faster(The annotated one). Could you please explain why?
